// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc47I0ATNYXiO3K60PkHsfQLY__9n4Ot4',
    appId: '1:1078135312921:web:6aca6c48a1628fb13b5088',
    messagingSenderId: '1078135312921',
    projectId: 'loja-virtual-completa-91219',
    authDomain: 'loja-virtual-completa-91219.firebaseapp.com',
    storageBucket: 'loja-virtual-completa-91219.appspot.com',
    measurementId: 'G-0XG4KD3TBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzJHCqRr1FSAsbFISKQQaEie1m5kI3PJQ',
    appId: '1:1078135312921:android:1de80184485a57da3b5088',
    messagingSenderId: '1078135312921',
    projectId: 'loja-virtual-completa-91219',
    storageBucket: 'loja-virtual-completa-91219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlBtzm6LoV3s8V8gyUOjgvMI1S1o2faUk',
    appId: '1:1078135312921:ios:df641b4a2beeebc33b5088',
    messagingSenderId: '1078135312921',
    projectId: 'loja-virtual-completa-91219',
    storageBucket: 'loja-virtual-completa-91219.appspot.com',
    iosClientId: '1078135312921-ug5e5mg55h1heljcbhbqta34imls8dih.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtualCompleta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlBtzm6LoV3s8V8gyUOjgvMI1S1o2faUk',
    appId: '1:1078135312921:ios:df641b4a2beeebc33b5088',
    messagingSenderId: '1078135312921',
    projectId: 'loja-virtual-completa-91219',
    storageBucket: 'loja-virtual-completa-91219.appspot.com',
    iosClientId: '1078135312921-ug5e5mg55h1heljcbhbqta34imls8dih.apps.googleusercontent.com',
    iosBundleId: 'com.example.lojaVirtualCompleta',
  );
}
